### ISSUE TITLE
Coda Status

### ISSUE THREAD

**Issue by AliRashidnejad** [amoshyc/posetrack18#1]
Hi, 
I was just wondering to ask if you have evaluated this code and it works ? I need such a baseline for my master thesis.

**Comment by amoshyc** [comment]
Sorry, this repo is deprecated and not functional. For baseline, you can check 2017 Winner [Detect and Track](https://github.com/facebookresearch/DetectAndTrack) or 2018 Winner [Simple Baseline](https://github.com/Microsoft/human-pose-estimation.pytorch/), though the latter does not provide their tracking code.
